spring:
  application:
    name: demo
    
  # Azure MySQL 데이터베이스 설정
  datasource:
    url: jdbc:mysql://db-guidely-summary-statstics.mysql.database.azure.com:3306/summary-statistics?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: appsummarystat
    password: AppSummaryPass#123
    
    # MySQL 연결 설정
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA 설정 (MySQL 용)
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        


# 로깅 설정
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      zaxxer:
        hikari: DEBUG 